--- 
eureka: 
  client: 
    fetchRegistry: false
    registerWithEureka: false
    service-url: 
      defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka/"
  instance: 
    hostname: localhost
  server: 
    waitTimeInMsWhenSyncEmpty: 0
server: 
  port: "${PORT:8761}"
spring: 
  application: 
    name: BatchEurekaServer
  profiles: 
    active: 
      - DEV
